# Eat Safe, Love

## Notebook Set Up

In [3]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [4]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [5]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [6]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [7]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [10]:
# Find the establishments with a hygiene score of 20
query = {"scores.Hygiene": 20}

# Use count_documents to display the number of documents in the result
print(f"There are {establishments.count_documents(query)} documents with a 'Hygiene' score of 20.")

# Display the first document in the results using pprint
results = establishments.find(query)
print("")
print("The first document is:")
print("-"*50)
pprint(results[0])

There are 41 documents with a 'Hygiene' score of 20.

The first document is:
--------------------------------------------------
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('67461c8bc0bdb47f8df7ecbf'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [37]:
# Retrieve all documents
results = list(establishments.find())

# Convert results to DataFrame
hygiene_df = pd.DataFrame(results)

# Display the number of rows
print("Number of rows:", len(hygiene_df))

# Display the first 10 rows
hygiene_df.head(5)

Number of rows: 38787

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,67461c8ac0bdb47f8df7d18d,1043695.0,0.0,PI/000073616,The Pavilion,Restaurant/Cafe/Canteen,1,East Cliff Pavilion,Wear Bay Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.195625, 'latitude': 51.083812}",,4591.765489,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,67461c8ac0bdb47f8df7d18e,647177.0,0.0,PI/000041489,Wear Bay Bowls Club,Pub/bar/nightclub,7843,Wear Bay Road,Folkestone,Kent,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.196408, 'latitude': 51.086058}",,4591.821311,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
2,67461c8ac0bdb47f8df7d18f,289353.0,0.0,PI/000002468,St Marys COE (aided) Primary School,School/college/university,7845,St Marys Church Of England Primary School,Warren Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 1.194762, 'latitude': 51.085797}",,4591.871474,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
3,67461c8ac0bdb47f8df7d192,289352.0,0.0,PI/000002460,The Ship,Pub/bar/nightclub,7843,23 The Stade,Folkestone,Kent,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.188537, 'latitude': 51.08084}",,4591.912145,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
4,67461c8ac0bdb47f8df7d193,289560.0,0.0,PI/000039927,Mariner,Pub/bar/nightclub,7843,16 The Stade,Folkestone,Kent,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.188537, 'latitude': 51.08084}",,4591.912145,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."

In [39]:
# Export DataFrame to csv file
hygiene_df.to_csv("Resources/hygiene_df.csv", index=False, header=True)

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [41]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {"LocalAuthorityName":{'$regex': "London"}, "RatingValue" : {'$gte':4}}

# Use count_documents to display the number of documents in the result
print(f"There are {establishments.count_documents(query)} documents for establishments within 'London' with a 'RatingValue' >= 4.")

# Display the first document in the results using pprint
results = establishments.find(query)
print("")
print("The first document is:")
print("-"*50)
pprint(results[0])

There are 33 documents for establishments within 'London' with a 'RatingValue' >= 4.

The first document is:
--------------------------------------------------
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('67461c8bc0bdb47f8df806da'),
 'geocode': {'latitude': 51.369321, 'longitude': 0.508551},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [43]:
# Retrieve all documents
results = list(establishments.find())

# Convert the result to a Pandas DataFrame
london_rating = pd.DataFrame(results)

# Export DataFrame to csv file
london_rating.to_csv("resources/london_rating.csv", index=False, header=True)


# Display the number of rows in the DataFrame
print(f"The number of rows in this DataFrame is: {len(london_rating)}")
print("")
# Display the first 10 rows of the DataFrame
london_rating.head()

The number of rows in this DataFrame is: 38787

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,67461c8ac0bdb47f8df7d18d,1043695.0,0.0,PI/000073616,The Pavilion,Restaurant/Cafe/Canteen,1,East Cliff Pavilion,Wear Bay Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.195625, 'latitude': 51.083812}",,4591.765489,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,67461c8ac0bdb47f8df7d18e,647177.0,0.0,PI/000041489,Wear Bay Bowls Club,Pub/bar/nightclub,7843,Wear Bay Road,Folkestone,Kent,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.196408, 'latitude': 51.086058}",,4591.821311,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
2,67461c8ac0bdb47f8df7d18f,289353.0,0.0,PI/000002468,St Marys COE (aided) Primary School,School/college/university,7845,St Marys Church Of England Primary School,Warren Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 1.194762, 'latitude': 51.085797}",,4591.871474,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
3,67461c8ac0bdb47f8df7d192,289352.0,0.0,PI/000002460,The Ship,Pub/bar/nightclub,7843,23 The Stade,Folkestone,Kent,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.188537, 'latitude': 51.08084}",,4591.912145,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
4,67461c8ac0bdb47f8df7d193,289560.0,0.0,PI/000039927,Mariner,Pub/bar/nightclub,7843,16 The Stade,Folkestone,Kent,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.188537, 'latitude': 51.08084}",,4591.912145,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [45]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score
# Extract the 'geocode' field from the document with 'BusinessName' 'Penang Flavours'
lat_long = establishments.find_one({"BusinessName":"Penang Flavours"},{"geocode":1})

degree_search = 0.01
latitude = lat_long['geocode']['latitude']
longitude = lat_long['geocode']['longitude']

query ={"geocode.latitude":{'$gte': latitude-degree_search, '$lte': latitude+degree_search},
        "geocode.longitude":{'$gte': longitude-degree_search, '$lte': longitude+degree_search},
        "RatingValue":5}
sort = [("scores.Hygiene",1)]
limit = 2

# Print the results
results = list(establishments.find(query).sort(sort).limit(limit))
for r in results:
    pprint(r)

{'AddressLine1': 'Restaurant And Premises 107A Plumstead High Street',
 'AddressLine2': '',
 'AddressLine3': 'Plumstead',
 'AddressLine4': 'Greenwich',
 'BusinessName': 'Howe and Co Fish and Chips - Van 17',
 'BusinessType': 'Mobile caterer',
 'BusinessTypeID': 7846,
 'ChangesByServerID': 0,
 'Distance': 4646.95593107927,
 'FHRSID': 1380578,
 'LocalAuthorityBusinessID': '14425',
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE18 1SE',
 'RatingDate': '2021-11-11T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('67461c8bc0bdb47f8df84501'),
 'geocode': {'latitude': 51.4875335693359, 'longitude': 0.0925370007753372},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/1380578',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}
{'AddressLine1': '144 - 146 Plumstead High Street',
 'AddressLine2': '',
 'AddressLine3': 'Plumstead',
 'AddressLine4': 'Greenwich',
 'BusinessName': 'Iceland',
 'BusinessType': 'Retailers - supermarkets/hypermarkets',
 'BusinessTypeID': 7840,
 'ChangesByServerID': 0,
 'Distance': 4646.946071297699,
 'FHRSID': 695223,
 'LocalAuthorityBusinessID': 'PI/000178842',
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE18 1JQ',
 'RatingDate': '2019-11-13T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('67461c8bc0bdb47f8df844f4'),
 'geocode': {'latitude': 51.4871482849121, 'longitude': 0.0924199968576431},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695223',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 5}}

In [46]:
# Convert result to Pandas DataFrame
near_penang_df = pd.DataFrame(results)

# Export DataFrame to csv file
near_penang_df.to_csv("resources/near_penang_df.csv", index=False, header=True)

near_penang_df.head (5)

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,67461c8bc0bdb47f8df84501,1380578,0,14425,Howe and Co Fish and Chips - Van 17,Mobile caterer,7846,Restaurant And Premises 107A Plumstead High St...,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.0925370007753372, 'latitude': ...",,4646.955931,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
1,67461c8bc0bdb47f8df844f4,695223,0,PI/000178842,Iceland,Retailers - supermarkets/hypermarkets,7840,144 - 146 Plumstead High Street,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0924199968576431, 'latitude': ...",,4646.946071,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [48]:
# Create a pipeline that:
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest
# Pipeline
match = {'$match': {"scores.Hygiene":0}}

group = {'$group': {"_id" : "$LocalAuthorityName",
                   "count": {'$sum':1}}}

sort = {'$sort':{"count":-1}}

pipeline = [match, group, sort]

results = list(establishments.aggregate(pipeline))
# Print the number of documents in the result
print(f"There are {len(results)} documents in the result.")

# Print the first 10 results
print("")
print("The first 10 documents are:")
print("-"*50)
pprint(results[0:10])

There are 55 documents in the result.

The first 10 documents are:
--------------------------------------------------
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [50]:
# Convert the result to a Pandas DataFrame
agg_df = pd.json_normalize(results)

# Export DataFrame to csv file
agg_df.to_csv("resources/aggregate_df.csv", index=False, header=True)

# Display the number of rows in the DataFrame
print(f"The number of rows in this DataFrame is: {len(agg_df)}")
print("")

# Display the first 10 rows of the DataFrame
agg_df.head(10)

The number of rows in this DataFrame is: 55

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542